# Interactive component
<html lang="en">
    
<head>
        <meta charset="utf-8">
        <title></title>
        <script src="https://d3js.org/d3.v6.js"></script>
        <style type ="text/css">

  .line1 {
        fill: none;
        stroke: steelblue;
        stroke-width: 2.0px;
      }
	  
	  .line18 {
        fill: none;
        stroke: green;
        stroke-width: 2.0px;
      }
	  
	  .line19 {
        fill: none;
        stroke: blue;
        stroke-width: 2.0px;
      }
	  .line20 {
        fill: none;
        stroke: red;
        stroke-width: 2.0px;
      }
	  
	  
	  #format1{
			  font-size:20px;
			  font-family:Palatino;}
			  
	  #format2{
			  font-size:15px;
			  font-family:Palatino;}
        </style>
		
		
      
    </head>
    
    <body>
    <svg width="800" height="500" id="svg3">
	<text id="format1" x="200" y="80">Total Bike Trips 2018-2020</text>
	</svg>
	
	  <svg width="800" height="500" id="svg4">
	<text id="format1" x="200" y="80">Total Bike Trips by Year</text>
	<text id="format2" x="200" y="100">Click year to run</text>
	<rect id="year18" x="100" y="140" width=80 height=40 fill="lightgreen"></rect>
	<rect id="year19" x="200" y="140" width=80 height=40 fill="steelblue"></rect>
	<rect id="year20" x="300" y="140" width=80 height=40 fill="pink"></rect>
	<text x="120" y="160">2018</text>
	<text x="220" y="160">2019</text>
	<text x="330" y="160">2020</text>
	

	  </svg>
	
    <svg width="800" height="600" id="svg1">
	<text id="format1" x="200" y="120">Number of Trips during Weekdays (in thousands)</text>
	</svg>
	
    <svg width="800" height="600" id="svg2">
	<text id="format1" x="200" y="160">Number of Trips during Weekends (in thousands)</text>
	</svg>
	
	  <svg width="800" height="50" id="svg6">
	 </svg>
	
    <svg width="1000" height="800" id="svg5">
	<text id="format1" x="200" y="20">Bike station trips</text>
	<text id="format2" x="350" y="60">Click 2019 data or 2020 data to show top 10 busiest stations</text>
	<image xlink:href="https://raw.githubusercontent.com/ds-eda-viz/NYC-Bike-Share/main/rendered_data/map.PNG" x="0" y="50" width="500" height="750"></image>
	<rect id="data_19" x="50" y="40" width="100" height="40" fill="steelblue"></rect>
	<rect id="data_20" x="200" y="40"  width="100" height="40" fill="pink"></rect>
	<text x="60" y="60">2019 data</text>
	<text x="210" y="60">2020 data</text>
	<text x="550" y="100">Total trips in thousand</text>
	</svg>
	
    
    <script>
      
	  var svg3 = d3.select("#svg3")
      var margin3 = {top: 100, right: 50, bottom: 30, left: 60}
      var width3 =  +svg3.attr("width") - margin3.left - margin3.right
      var height3 = +svg3.attr("height") - margin3.top - margin3.bottom
      var g3 = svg3.append("g").attr("transform", `translate(${margin3.left}, ${margin3.top})`);
      var parseTime = d3.timeParse("%b-%y");
      var xScale3 = d3.scaleTime().range([0, width3]);
      var yScale3 = d3.scaleLinear()
        .domain([70000, 3000000])
        .range([height3, 0]);
      var line3 = d3.line()
        .x(d => xScale3(d.date))
        .y(d => yScale3(d.high));
      var data3 = 
      [{"date":"Jan-18","high":718994},
		{"date":"Feb-18","high":843114},
		{"date":"Mar-18","high":976672},
		{"date":"Apr-18","high":1307543},
		{"date":"May-18","high":1824710},
		{"date":"Jun-18","high":1953103},
		{"date":"Jul-18","high":1913625},
		{"date":"Aug-18","high":1977177},
		{"date":"Sep-18","high":1877884},
		{"date":"Oct-18","high":1878657},
		{"date":"Nov-18","high":1260355},
		{"date":"Dec-18","high":1016505},
		{"date":"Jan-19","high":967287},
		{"date":"Feb-19","high":943744},
		{"date":"Mar-19","high":1327960},
		{"date":"Apr-19","high":1766094},
		{"date":"May-19","high":1924563},
		{"date":"Jun-19","high":2125370},
		{"date":"Jul-19","high":2181064},
		{"date":"Aug-19","high":2344224},
		{"date":"Sep-19","high":2444900},
		{"date":"Oct-19","high":2092573},
		{"date":"Nov-19","high":1478708},
		{"date":"Dec-19","high":955210},
		{"date":"Jan-20","high":1240596},
		{"date":"Feb-20","high":1146830},
		{"date":"Mar-20","high":1068457},
		{"date":"Apr-20","high":682762},
		{"date":"May-20","high":1487890},
		{"date":"Jun-20","high":1882273},
		{"date":"Jul-20","high":2105808},
		{"date":"Aug-20","high":2329514},
		{"date":"Sep-20","high":2488225},
		{"date":"Oct-20","high":2248869}];
		
      data3.forEach(function(d) {
            d.date = parseTime(d.date);
      });
     
      xScale3
        .domain(d3.extent(data3, d => d.date));
        
      g3.append("g")
          .attr("transform", `translate(0, ${height3})`)
          .call(d3.axisBottom(xScale3).ticks(18));
      g3.append("g")
          .call(d3.axisLeft(yScale3));
      g3.append("path")
          .datum(data3)
          .attr("class", "line1")
          .attr("fill", "none")
          .attr("d", line3);
		  
	  let totalLength1 = svg3.select('.line1').node().getTotalLength();

	  svg3.select('.line1')
		.attr("stroke-dasharray", totalLength1 + " " + totalLength1)
		.attr("stroke-dashoffset", totalLength1)
		.transition() // Call Transition Method
		.duration(2000) // Set Duration timing (ms)
		.ease(d3.easeLinear) // Set Easing option
		.attr("stroke-dashoffset", 0); 
		
		
//////////////////////////////////////////////////////////////////////// 
var svg4 = d3.select("#svg4")
      var margin4 = {top: 100, right: 50, bottom: 30, left: 60}
      var width4 =  +svg4.attr("width") - margin4.left - margin4.right
      var height4 = +svg4.attr("height") - margin4.top - margin4.bottom
      var g4 = svg4.append("g").attr("transform", `translate(${margin4.left}, ${margin4.top})`);
	  
      var parseTime4 = d3.timeParse("%b");
      var xScale4 = d3.scaleTime().range([0, width4]);
      var yScale4 = d3.scaleLinear()
        .domain([70000, 3000000])
        .range([height4, 0]);
      var line4 = d3.line()
        .x(d => xScale4(d.date))
        .y(d => yScale4(d.high));
      var data18 = 
      [{"date":"Jan","high":718994},
		{"date":"Feb","high":843114},
		{"date":"Mar","high":976672},
		{"date":"Apr","high":1307543},
		{"date":"May","high":1824710},
		{"date":"Jun","high":1953103},
		{"date":"Jul","high":1913625},
		{"date":"Aug","high":1977177},
		{"date":"Sep","high":1877884},
		{"date":"Oct","high":1878657},
		{"date":"Nov","high":1260355},
		{"date":"Dec","high":1016505}
		];
	    var data19 = 
      [{"date":"Jan","high":967287},
		{"date":"Feb","high":943744},
		{"date":"Mar","high":1327960},
		{"date":"Apr","high":1766094},
		{"date":"May","high":1924563},
		{"date":"Jun","high":2125370},
		{"date":"Jul","high":2181064},
		{"date":"Aug","high":2344224},
		{"date":"Sep","high":2444900},
		{"date":"Oct","high":2092573},
		{"date":"Nov","high":1478708},
		{"date":"Dec","high":955210}
		];
		var data20=
		[{"date":"Jan","high":1240596},
		{"date":"Feb","high":1146830},
		{"date":"Mar","high":1068457},
		{"date":"Apr","high":682762},
		{"date":"May","high":1487890},
		{"date":"Jun","high":1882273},
		{"date":"Jul","high":2105808},
		{"date":"Aug","high":2329514},
		{"date":"Sep","high":2488225},
		{"date":"Oct","high":2248869}];
		
      data18.forEach(function(d) {
            d.date = parseTime4(d.date);
      });
      data19.forEach(function(d) {
            d.date = parseTime4(d.date);
      });
	  data20.forEach(function(d) {
            d.date = parseTime4(d.date);
      });
      xScale4
        .domain(d3.extent(data18, d => d.date));
        
      g4.append("g")
          .attr("transform", `translate(0, ${height4})`)
          .call(d3.axisBottom(xScale4).ticks(18));
      g4.append("g")
          .call(d3.axisLeft(yScale4))
      g4.append("path")
          .datum(data18)
          .attr("class", "line18")
          .attr("fill", "none")
          .attr("d", line4);
	
      g4.append("path")
          .datum(data19)
          .attr("class", "line19")
          .attr("fill", "none")
          .attr("d", line4);
	
	  g4.append("path")
          .datum(data20)
          .attr("class", "line20")
          .attr("fill", "none")
          .attr("d", line4);
	  
	  let totalLength18 = svg4.select('.line18').node().getTotalLength();
	  let totalLength19 = svg4.select('.line19').node().getTotalLength();
	  let totalLength20 = svg4.select('.line20').node().getTotalLength();
	  
	  svg4.select("#year18")
		  .on("click", function() {
			svg4.select('.line18')
			.attr("stroke-dasharray", totalLength18 + " " + totalLength18)
			.attr("stroke-dashoffset", totalLength18)
			.transition() // Call Transition Method
			.duration(2000) // Set Duration timing (ms)
			.ease(d3.easeLinear) // Set Easing option
			.attr("stroke-dashoffset", 0); 
			  });
	  
	  svg4.select("#year19")
		  .on("click", function() {
			svg4.select('.line19')
			.attr("stroke-dasharray", totalLength19 + " " + totalLength19)
			.attr("stroke-dashoffset", totalLength19)
			.transition() // Call Transition Method
			.duration(2000) // Set Duration timing (ms)
			.ease(d3.easeLinear) // Set Easing option
			.attr("stroke-dashoffset", 0); 
			  });
	 svg4.select("#year20")
		  .on("click", function() {
			svg4.select('.line20')
			.attr("stroke-dasharray", totalLength20 + " " + totalLength20)
			.attr("stroke-dashoffset", totalLength20)
			.transition() // Call Transition Method
			.duration(2000) // Set Duration timing (ms)
			.ease(d3.easeLinear) // Set Easing option
			.attr("stroke-dashoffset", 0); 
			  });


////////////////////////////////////////////////////////////////////////
	  
      var svg1 = d3.select("#svg1")
      var margin = {top: 150, right: 50, bottom: 50, left: 50}
      var width =  svg1.attr("width") - margin.left - margin.right
      var height = svg1.attr("height") - margin.top - margin.bottom
      var g1 = svg1.append("g").attr("transform", `translate(${margin.left}, ${margin.top})`);

      var xScale = d3.scaleBand().domain(d3.range(24)).range([0, width]).paddingInner(0.05);
      var yScale = d3.scaleLinear().domain([0, 4000]).range([height, 0]);
        
      var xAxis = d3.axisBottom(xScale);
      var yAxis = d3.axisLeft(yScale);
      
      g1.append("g").attr("transform", `translate(0, ${height})`).call(xAxis);
      g1.append("g").call(yAxis);
      g1.append("g").call(yAxis);
      
      var readfile = function(d){
        return {
          is_weekend: d.is_weekend,
          hour: d.hour,
          trips: d.total_num_trips/1000 
        }
      };
      
      d3.csv("https://raw.githubusercontent.com/ds-eda-viz/NYC-Bike-Share/main/rendered_data/weekend_weekday_dist.csv", readfile)
        .then(function(data){
          
          var weekday = data.filter(function(d) {return d.is_weekend == "weekday";});
          var bars = g1.selectAll(".bar").data(weekday).enter().append("rect").attr("class", "bar")
          
          bars.attr("x", function(d) {return xScale(d.hour);})
          .attr("y", function(d) {return yScale(d.trips);})
          .attr("width", xScale.bandwidth()*0.95)
          .attr("height", function(d) {return height - yScale(d.trips)})
          .attr("fill", "steelblue")
          .on("mouseover", function(){ d3.select(this).attr("fill", "orange");})
		  
          .on("mouseout", function(){ d3.select(this).attr("fill", "steelblue");});
          
         
          
        });
        
      ///////////////////////////////////////////////////////////////////
      
      var svg = d3.select("#svg2")
      var margin = {top: 150, right: 50, bottom: 50, left: 50}
      var width =  svg.attr("width") - margin.left - margin.right
      var height = svg.attr("height") - margin.top - margin.bottom
      var g2 = svg.append("g").attr("transform", `translate(${margin.left}, ${margin.top})`);
      
      var xScale = d3.scaleBand().domain(d3.range(24)).range([0, width]);
      var yScale = d3.scaleLinear().domain([0, 4000]).range([height, 0]);
        
      var xAxis = d3.axisBottom(xScale);
      var yAxis = d3.axisLeft(yScale);
      
      g2.append("g").attr("transform", `translate(0, ${height})`).call(xAxis);
      g2.append("g").call(yAxis)
      
      d3.csv("https://raw.githubusercontent.com/ds-eda-viz/NYC-Bike-Share/main/rendered_data/weekend_weekday_dist.csv", readfile)
        .then(function(data){
          var weekend = data.filter(function(d) {return d.is_weekend == "weekend";})
          var bars = g2.selectAll(".bar").data(weekend).enter().append("rect").attr("class", "bar")
          
          bars.attr("x", function(d) {return xScale(d.hour);})
          .attr("y", function(d) {return yScale(d.trips);})
          .attr("width", xScale.bandwidth()*0.95)
          .attr("height", function(d) {return height - yScale(d.trips)})
          .attr("fill", "steelblue")
          .on("mouseover", function(){ d3.select(this).attr("fill", "orange");})
          .on("mouseout", function(){ d3.select(this).attr("fill", "steelblue");});
          
         
        });
//////////////////////////////////////////////////////////////////////
var svg5=d3.select("#svg5");
			var station_2019=[{"key":"A", x:225, y:450, t:157, name: "Pershing Square North", sid: "Top1"},
			{"key":"B", x:175, y:550, t:122, name: "E 17 St & Broadway", sid: "Top2"},
			{"key":"C", x:150, y:460, t:120, name: "8 Ave & W 31 St", sid: "Top3"},
			{"key":"D", x:175, y:520, t:113, name: "Broadway & E 22 St", sid: "Top4"},
			{"key":"E", x:170, y:520, t:113, name: "Broadway & E 14 St", sid: "Top5"},
			{"key":"F", x:145, y:510, t:110, name: "W 21 St & 6 Ave", sid: "Top6"},
			{"key":"G", x:70, y:650,  t:106, name: "West St & Chambers St", sid: "Top7"},
			{"key":"H", x:210, y:360, t:103, name: "Broadway & W 60 St", sid: "Top8"},
			{"key":"I", x:100, y:570, t:101, name: "Christopher St & Greenwich St", sid: "Top9"},
			{"key":"J", x:120, y:410, t:99, name: "12 Ave & W 40 St", sid: "Top10"}];
			
			var station_2020=[{"key":"A", x:70, y:650, t:88, name: "West St & Chambers St", sid: "Top1"},
			{"key":"B", x:120, y:410, t:88, name: "12 Ave & W 40 St", sid: "Top2"},
			{"key":"C", x:145, y:510, t:84, name: "W 21 St & 6 Ave", sid: "Top3"},
			{"key":"D", x:318, y:375, t:84, name: "1 Ave & E 68 St", sid: "Top4"},
			{"key":"E", x:210, y:360, t:79, name: "Broadway & W 60 St", sid: "Top5"},
			{"key":"F", x:175, y:550, t:76, name: "E 17 St & Broadway", sid: "Top6"},
			{"key":"G", x:100, y:570, t:74, name: "Christopher St & Greenwich St", sid: "Top7"},
			{"key":"H", x:220, y:580, t:72, name: "E 13 St & Avenue A", sid: "Top8"},
			{"key":"I", x:80, y:580, t:71, name: "Pier 40 - Hudson River Park", sid: "Top9"},
			{"key":"J", x:175, y:520, t:68, name: "Broadway & E 22 St", sid: "Top10"}];

	        
			svg5.append("g").attr("id","rects")
				.selectAll("rect")
				.data(station_2019, d=>d.key)
				.enter()
				.append("rect")
				.attr("x","525")
				.attr("y",(d,i)=>i*60+150)
				.attr("width",d=>(d.t))
				.attr("height",40)
				.attr("fill","steelblue");
				
			svg5.append("g").attr("id", "texts")
			    .selectAll("text")
				.data(station_2019, d=>d.key)
				.enter()
				.append("text")
				.attr("x",d=>d.t+535)
				.attr("y",(d,i)=>i*60+165)
				.text(d=> `Trips: ${d.t}, ${d.sid}`)
				.style("font-size", '10px');
				
			svg5.append("g").attr("id", "textsadd")
			    .selectAll("text")
				.data(station_2019, d=>d.key)
				.enter()
				.append("text")
				.attr("x",d=>d.t+535)
				.attr("y",(d,i)=>i*60+180)
				.text(d=> `${d.name}`)
				.style("font-size", '10px');
				
			svg5.append("g").attr("id","circles")
			    .selectAll("circle")
				.data(station_2019, d=>d.key)
				.enter()
				.append("circle")
				.attr("cx",d=>d.x)
				.attr("cy",d=>d.y)
				.attr("r", 8)
				.attr("fill", "blue");	
				
			svg5.append("g").attr("id","texts_c")
			    .selectAll("text")
				.data(station_2019, d=>d.key)
				.enter()
				.append("text")
				.attr("x",d=>d.x)
				.attr("y",d=>d.y-10)
				.text(d=> `${d.sid}`)
				.style('fill', 'blue');
			
			function changeyear_19(){
			
				rects1=d3.select("#svg5").select("#rects")
				.selectAll("rect")
				.data(station_2019, d=>d.key);
				
			   texts1=d3.select("#svg5").select("#texts")
				.selectAll("text")
				.data(station_2019, d=>d.key);
				
			   textsadd1=d3.select("#svg5").select("#textsadd")
				.selectAll("text")
				.data(station_2019, d=>d.key);
				
				
			   circles1=d3.select("#svg5").select("#circles")
				.selectAll("circle")
				.data(station_2019, d=>d.key);
				
			   texts_c1=d3.select("#svg5").select("#texts_c")
				.selectAll("text")
				.data(station_2019, d=>d.key);
			   
			   rects1.enter()
				.append("rect")
				.merge(rects1)
				.attr("x","525")
				.attr("y",(d,i)=>i*60+150)
				.attr("width",d=>d.t)
				.attr("height",40)
				.transition()
				.duration(500)
				.attr("fill","steelblue");
				
				rects1.exit().remove();	
				
			
			   texts1.enter()
				.append("text")
				.merge(texts1)
				.attr("x",d=>d.t+535)
				.attr("y",(d,i)=>i*60+165)
				.text(d=> `Trips: ${d.t}, ${d.sid}`)
				.style("font-size", '10px');
		
				
				texts1.exit().remove();	
				
			    textsadd1.enter()
				.append("text")
				.merge(textsadd1)
				.attr("x",d=>d.t+535)
				.attr("y",(d,i)=>i*60+180)
				.text(d=> `${d.name}`)
				.style("font-size", '10px');
		
				textsadd1.exit().remove();	
				
				
			   circles1.enter()
				.append("circle")
				.merge(circles1)
				.attr("cx",d=>d.x)
				.attr("cy",d=>d.y)
				.attr("r", 8)
				.attr("fill", "blue");	
				
				circles1.exit().remove();	
				
			   texts_c1.enter()
				.append("text")
				.merge(texts_c1)
				.attr("x",d=>d.x)
				.attr("y",d=>d.y-10)
				.text(d=> `${d.sid}`)
				.style('fill', 'blue');
				
				texts_c1.exit().remove();	
		
			};
			
			
			function changeyear_20(){
			   
			   rects2=d3.select("#svg5").select("#rects")
				.selectAll("rect")
				.data(station_2020, d=>d.key);
				
			   texts2=d3.select("#svg5").select("#texts")
				.selectAll("text")
				.data(station_2020, d=>d.key);
				
			   textsadd2=d3.select("#svg5").select("#textsadd")
				.selectAll("text")
				.data(station_2020, d=>d.key);
				
			   circles2=d3.select("#svg5").select("#circles")
				.selectAll("circle")
				.data(station_2020, d=>d.key);
				
			  texts_c2=d3.select("#svg5").select("#texts_c")
				.selectAll("text")
				.data(station_2020, d=>d.key);
				
			   rects2.enter()
				.append("rect")
				.merge(rects2)
				.attr("x","525")
				.attr("y",(d,i)=>i*60+150)
				.attr("width",d=>d.t)
				.attr("height",40)
				.transition()
				.duration(500)
				.attr("fill","pink");
				
				rects2.exit().remove();	
				
				
				texts2.enter()
				.append("text")
				.merge(texts2)
				.attr("x",d=>d.t+535)
				.attr("y",(d,i)=>i*60+165)
				.text(d=> `Trips: ${d.t}, ${d.sid}`)
				.style("font-size", '10px');
				
				texts2.exit().remove();	
				
				
				textsadd2.enter()
				.append("text")
				.merge(textsadd2)
				.attr("x",d=>d.t+535)
				.attr("y",(d,i)=>i*60+180)
				.text(d=> `${d.name}`)
				.style("font-size", '10px');
		
				textsadd2.exit().remove();	
				
				circles2.enter()
				.append("circle")
				.merge(circles2)
				.attr("cx",d=>d.x)
				.attr("cy",d=>d.y)
				.attr("r", 8)
				.attr("fill", "red");	
				
				circles2.exit().remove();	
				
				texts_c2.enter()
				.append("text")
				.merge(texts_c2)
				.attr("x",d=>d.x)
				.attr("y",d=>d.y-10)
				.text(d=> `${d.sid}`)
				.style('fill', 'red');
				
				texts_c2.exit().remove();
				};
				
			d3.select("#svg5").select("#data_19")
			.on("click",changeyear_19);
			
			d3.select("#svg5").select("#data_20")
			.on("click",changeyear_20);
				
    </script>
    
    </body>

</html>