# Conclusion

Everyday we see people ride bikes pass us and take tours in New York City, but few of us spend time on studying this system. By using the R and D3 programming in our exploratory data analysis class. Four of us are able to perform a deep analysis on the bike usage daily, monthly and yearly. There are a lot of interesting part for this system.

1. Male riders are more then female riders among all age levels, people between 30 - 35 groups are riding bikes more than other 
groups. Although female rides has less trips, average trip duration is longer than male riders. In 2020, trip duration is longer 
than average duration in 2018, 2019. More people would rely on the bike as their commute tools in this year.

2. In a normal year, bike usage would be increased from March to September, but the lock down in April and May 2020 caused the 
readerships reduced significantly. After the lock down which is June, we see the ridership has a huge amount of usage this year.
People might do not have confidence to take Subway and Bus, so they choose to ride the bike for commuting.

3. The route pattern is another interesting part we want to point out. In 2018 and 2019, few people would ride bikes to cross 
boroughs. We see an increase in 2020, more and more people would ride bikes from Brooklyn or Queens to Manhattan. As the social 
distance policy implements in New York City, people tend to take bikes for their work. 

4. By analyzing the most popular bike stations, we come with a conclusion that people do not travel to New York City this year.
As the center of the pandemic, New York City has closed restaurants, gym, public libraries, movie theaters and shopping stores. 
Both retail and travel industry would suffer a huge loss from this year due to the pandemic. 

Very soon, there will be single digit number of days left for the year of 2020, People who live in this city would never forget 
about this year. We will remember how this pandemic changed our lives forever, and friends and families we have lost forever. We 
believe our city will recover from it and life will be back to normal. It's maybe a long wait, but we believe it.




